SpectrumWorxCompleteSDK: ModuleChain Class Reference
ModuleChain Class Reference
Engine
A linear list-like container of modules.
Public Member Functions
bool insertBefore (ModulePtr const &pFollowingModule, ModulePtr const &pNewModule)
bool insertAfter (ModulePtr const &pPrecedingModule, ModulePtr const &pNewModule)
bool append (ModulePtr const &pModule)
bool prepend (ModulePtr const &pModule)
void remove (ModulePtr const &pModule)
void reverse ()
void shiftBackwards (unsigned int amount=1)
void shiftForward (unsigned int amount=1)
void swap (ModulePtr const &, ModulePtr const &)
void clear ()
unsigned int size () const
bool empty () const
ModulePtr operator[] (unsigned int moduleIndex)
Detailed Description
A linear list-like container of modules.
Note
All preconditions are validated with asserts in debug/development builds. Violating a precondition in release builds results in undefined behaviour.
Functions that insert modules into the chain perform dynamic memory allocation as part of the module setup. These therefore return a bool to indicate success or failure (to allocate memory for the inserted module).
ModuleChain instances retain/release ownership of inserted/removed modules:
shared pointers are used to pass module instance parameters instead of plain references to emphasize this shared ownership semantics
all pointers are assumed to be non-null.
Member Function Documentation
bool insertBefore (ModulePtr const & pFollowingModule, ModulePtr const & pNewModule)
Effect: Inserts newModule before/in front of followingModule.
Preconditions:
- followingModule must already be in the chain
- newModule can already be in the chain but must not already be inserted in another chain
Complexity: Constant.
References ModuleChain::insertBefore().
Referenced by ModuleChain::insertBefore().
bool insertAfter (ModulePtr const & pPrecedingModule, ModulePtr const & pNewModule)
Effect: Inserts newModule after/behind precedingModule.
Preconditions:
- precedingModule must already be in the chain
- newModule can already be in the chain but must not already be inserted in another chain
Complexity: Constant.
References ModuleChain::insertAfter().
Referenced by ModuleChain::insertAfter().
bool append (ModulePtr const & pModule)
Effect: Inserts/appends a module at the end of the chain.
Preconditions: module can already be in the chain but must not already be inserted in another chain.
Complexity: Constant.
References ModuleChain::append().
Referenced by ModuleChain::append().
bool prepend (ModulePtr const & pModule)
Effect: Inserts/prepends a module at the beginning of the chain.
Preconditions: module can already be in the chain but must not already be inserted in another chain.
Complexity: Constant.
References ModuleChain::prepend().
Referenced by ModuleChain::prepend().
void remove (ModulePtr const & pModule)
Effect: Removes a module from the chain.
Preconditions: module must be in the chain.
Complexity: Constant.
void reverse ()
Effect: Reverses the order of modules in the chain.
Complexity: Linear.
void shiftBackwards (unsigned int amount = 1)
Effect: Moves backwards all the modules, so that the first module becomes the second, the second becomes the third... the last module becomes the first one. The shift is circular so if amount is larger than size() it will simply wrap around.
Complexity: Linear.
void shiftForward (unsigned int amount = 1)
Effect: Moves forwards all the modules, so that the second module becomes the first, the third becomes the second... the first module becomes the last one. The shift is circular so if amount is larger than size() it will simply wrap around.
Complexity: Linear.
void swap (ModulePtr const & , ModulePtr const &)
Effect: Swaps the positions of the two modules.
Preconditions: Both modules must be in the chain.
Complexity: Constant.
void clear ()
Effect: Removes all modules from the chain.
Complexity: Linear.
unsigned int size () const
Effect: Returns the number of modules contained in the chain.
Complexity: Linear.
bool empty () const
Effect: Returns true if the chain contains no modules.
Complexity: Constant.
ModulePtr operator[] (unsigned int moduleIndex)
Effect: Returns a pointer to the module at the position given by moduleIndex.
Preconditions: moduleIndex must be less than size().
Complexity: Linear.